# GitHub Sponsors configuration
# Uncomment and add your usernames to enable funding buttons

# github: [felixgeelhaar]
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ['https://example.com', 'https://example2.com']
