name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - API Reference
        - Getting Started Guide
        - Usage Examples
        - TypeScript Types
        - Error Messages
        - Migration Guide
        - README
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package's documentation is affected?
      options:
        - "@felixgeelhaar/jira-sdk"
        - "@felixgeelhaar/sdk-core"
        - "Repository/General"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located?
      placeholder: "README.md, packages/jira/src/services/issues.ts, etc."
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the documentation?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Outdated content
        - Broken link
        - Typo/Grammar
        - Missing example
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue in detail.
      placeholder: The documentation doesn't explain...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Documentation
      description: What should the documentation say or include?
      placeholder: The documentation should explain...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a specific suggestion for how to improve the documentation, please share it.
      placeholder: |
        Here's a suggested improvement:

        ```markdown
        ## New section
        ...
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples.
